// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	ID               int    `json:"id"`
	FirstName        string `json:"FirstName"`
	LastName         string `json:"LastName"`
	Age              string `json:"Age"`
	Gender           string `json:"Gender"`
	Dob              string `json:"DOB"`
	Mobile           string `json:"Mobile"`
	Email            string `json:"Email"`
	PermanentAddress string `json:"PermanentAddress"`
}

type Query struct {
}

type User struct {
	ID               int    `json:"id"`
	FirstName        string `json:"FirstName"`
	LastName         string `json:"LastName"`
	Age              string `json:"Age"`
	Gender           string `json:"Gender"`
	Dob              string `json:"DOB"`
	Mobile           string `json:"Mobile"`
	Email            string `json:"Email"`
	PermanentAddress string `json:"PermanentAddress"`
}

type UpdateUser struct {
	ID     int    `json:"id"`
	Mobile string `json:"Mobile"`
	Email  string `json:"Email"`
}
